#!/usr/bin/env bash
# ============================================================================
# niri_monitor_apply.sh - apply a saved layout to generated/outputs.kdl
# ============================================================================
# Reads the shared equisdots monitor layout and rewrites it as niri `output`
# blocks, then reloads. The saved file is the Hyprland-shaped line format:
#
#   desc|x|y|scale|mode|transform|vrr|bitdepth|cm|mirror|disabled
#
# Field mapping to niri:
#   desc      -> output "make model serial" (the same EDID identity Hyprland
#                stored; niri matches a monitor by connector name or this string)
#   x,y       -> position x=X y=Y
#   scale     -> scale S
#   mode      -> mode "WxH@R" (normalized to three decimals)
#   transform -> transform "normal|90|180|270|flipped|flipped-90|..."
#   vrr       -> variable-refresh-rate (1) / variable-refresh-rate on-demand=true (2)
#   disabled  -> off
#   bitdepth, cm, mirror -> no niri 26.04 equivalent; skipped with a comment
#
# Usage:
#   niri_monitor_apply.sh [LAYOUT_FILE]
#   niri_monitor_apply.sh --help
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'EOF'
Usage: niri_monitor_apply.sh [LAYOUT_FILE]

  LAYOUT_FILE  pipe-separated layout (default ~/.config/hypr/display-config)
               and its .bak fallback if the main file is empty.

Writes ~/.config/niri/generated/outputs.kdl and reloads niri.
EOF
    exit 0
fi

STATE_DIR="${EQUISDOTS_CONFIG_DIR}"
DEFAULT_STATE="$STATE_DIR/display-config"
DEFAULT_BAK="$STATE_DIR/display-config.bak"
LAYOUT="${1:-}"

if [[ -z "$LAYOUT" ]]; then
    if [[ -s "$DEFAULT_STATE" ]]; then
        LAYOUT="$DEFAULT_STATE"
    elif [[ -s "$DEFAULT_BAK" ]]; then
        LAYOUT="$DEFAULT_BAK"
    else
        die "no saved layout found ($DEFAULT_STATE)"
    fi
fi
[[ -r "$LAYOUT" ]] || die "cannot read layout: $LAYOUT"

ensure_dir "$NIRI_GENERATED_DIR"
OUT="$NIRI_GENERATED_DIR/outputs.kdl"
TMP="$NIRI_GENERATED_DIR/.outputs.$$"

# mode_norm MODE: normalize "WxH@RHz" to "WxH@R.xxx"; empty for auto/highrr.
mode_norm() {
    local m="$1"
    if [[ "$m" =~ ^([0-9]+x[0-9]+)@([0-9]+(\.[0-9]+)?)Hz?$ ]]; then
        printf '%s@%s' "${BASH_REMATCH[1]}" "$(awk -v r="${BASH_REMATCH[2]}" 'BEGIN { printf "%.3f", r }')"
    elif [[ "$m" =~ ^[0-9]+x[0-9]+(@[0-9]+\.[0-9]+)?$ ]]; then
        printf '%s' "$m"
    else
        printf ''
    fi
}

# transform_norm N: map the Hyprland integer to the niri string.
transform_norm() {
    case "$1" in
        1) printf '90' ;;
        2) printf '180' ;;
        3) printf '270' ;;
        4) printf 'flipped' ;;
        5) printf 'flipped-90' ;;
        6) printf 'flipped-180' ;;
        7) printf 'flipped-270' ;;
        *) printf 'normal' ;;
    esac
}

{
    printf '// Generated by niri_monitor_apply.sh from %s - do not edit.\n' "$LAYOUT"
    while IFS='|' read -r desc x y scale mode transform vrr bitdepth cm mirror disabled; do
        [[ -z "$desc" || "$desc" == \#* ]] && continue
        # Pad optional trailing fields (old 5-field files).
        transform="${transform:-0}"
        vrr="${vrr:-0}"
        disabled="${disabled:-0}"

        printf 'output "%s" {\n' "$desc"

        if [[ "$disabled" == "1" ]]; then
            printf '    off\n'
        else
            nmode="$(mode_norm "$mode")"
            [[ -n "$nmode" ]] && printf '    mode "%s"\n' "$nmode"
            [[ -n "$scale" ]] && printf '    scale %s\n' "$scale"
            printf '    position x=%s y=%s\n' "${x:-0}" "${y:-0}"
            [[ "$transform" != "0" ]] && printf '    transform "%s"\n' "$(transform_norm "$transform")"
            if [[ "$vrr" == "2" ]]; then
                printf '    variable-refresh-rate on-demand=true\n'
            elif [[ "$vrr" == "1" ]]; then
                printf '    variable-refresh-rate\n'
            fi
        fi

        # No niri 26.04 equivalent: bitdepth, color management preset, mirror.
        [[ -n "$bitdepth" && "$bitdepth" != "8" ]] && printf '    // bitdepth %s: no niri output option in 26.04\n' "$bitdepth"
        [[ -n "$cm" && "$cm" != "auto" ]] && printf '    // color-management %s: no niri output option in 26.04\n' "$cm"
        [[ -n "$mirror" ]] && printf '    // mirror %s: unsupported in niri 26.04 (use wl-mirror as a window)\n' "$mirror"

        printf '}\n'
    done <"$LAYOUT"
} >"$TMP"

mv -f "$TMP" "$OUT"
log "wrote $OUT"

# Validate before reloading so a bad fragment cannot break the running session.
if niri_validate; then
    niri_reload
else
    warn "niri validate failed after writing $OUT; not reloading"
fi
