#!/usr/bin/env bash
# ============================================================================
# niri_effects.sh - window-effect knobs for niri (gaps/border/blur/shadow)
# ============================================================================
# Port of shell/core/scripts/hypr-effects.sh. Hyprland could patch options live
# with `hyprctl eval`; niri has no runtime option setter, so every change is
# written to generated/theme-effects.kdl and the config is reloaded. niri
# reloads are cheap but not per-frame, so callers should throttle (for example
# on slider release rather than on every value change).
#
# Verbs:
#   read                print key=value for every known knob
#   preview KEY=VAL ... merge the values into the state and write + reload
#   persist             rewrite generated/theme-effects.kdl from the state
#   apply KEY=VAL ...   preview + persist (same file, so equivalent)
#
# State lives at ~/.config/niri/window-effects.json and is seeded from the
# values in modules/layout.kdl + config.kdl the first time. A partial change
# never clobbers the other knobs.
#
# Environment:
#   NIRI_NO_RELOAD=1   write the KDL but do not call niri (tests)
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

# Help must work even without niri/jq installed.
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: niri_effects.sh read | preview KEY=VAL ... | persist | apply KEY=VAL ..."
    echo "Known keys: gaps_in gaps_out border_size blur_size blur_passes shadow_range shadow_offset_x shadow_offset_y"
    exit 0
fi

require_cmd jq

STATE="$NIRI_EFFECTS_STATE"
OUT="$NIRI_GENERATED_DIR/theme-effects.kdl"

ensure_dir "$NIRI_CONFIG_DIR" "$NIRI_GENERATED_DIR"

# Known knobs and their defaults (matching modules/layout.kdl and config.kdl).
# shadow_render_power is accepted and stored but has no niri equivalent.
DEFAULTS='{
  "gaps_in": 16,
  "gaps_out": 25,
  "border_size": 2,
  "blur_size": 3,
  "blur_passes": 3,
  "shadow_range": 35,
  "shadow_render_power": 5,
  "shadow_offset_x": 0,
  "shadow_offset_y": 10
}'

seed_state() {
    [[ -f "$STATE" ]] && return 0
    printf '%s\n' "$DEFAULTS" >"$STATE"
}

# val STATE KEY DEFAULT: read a numeric value with a fallback.
val() {
    local state="$1" key="$2" def="$3"
    jq -r --arg k "$key" --arg d "$def" '.[$k] // ($d | tonumber)' <<<"$state" 2>/dev/null || printf '%s' "$def"
}

write_kdl() {
    local state="$1"
    local gaps_in gaps_out border_size blur_size blur_passes shadow_range ox oy strut
    gaps_in="$(val "$state" gaps_in 16)"
    gaps_out="$(val "$state" gaps_out 25)"
    border_size="$(val "$state" border_size 2)"
    blur_size="$(val "$state" blur_size 3)"
    blur_passes="$(val "$state" blur_passes 3)"
    shadow_range="$(val "$state" shadow_range 35)"
    ox="$(val "$state" shadow_offset_x 0)"
    oy="$(val "$state" shadow_offset_y 10)"

    # gaps_out is emulated with struts: struts = gaps_out - gaps_in (>= 0), so
    # the effective outer gap is gaps + struts and the inner gap stays gaps.
    strut="$(awk -v go="$gaps_out" -v gi="$gaps_in" 'BEGIN { d = go - gi; if (d < 0) d = 0; print d }')"

    local tmp="$NIRI_GENERATED_DIR/.theme-effects.$$"
    {
        printf '// Generated by niri_effects.sh - do not edit.\n'
        printf 'layout {\n'
        printf '    gaps %s\n' "$gaps_in"
        printf '    struts {\n'
        printf '        left %s\n' "$strut"
        printf '        right %s\n' "$strut"
        printf '        top %s\n' "$strut"
        printf '        bottom %s\n' "$strut"
        printf '    }\n'
        printf '    border {\n'
        printf '        width %s\n' "$border_size"
        printf '    }\n'
        printf '    shadow {\n'
        printf '        softness %s\n' "$shadow_range"
        printf '        offset x=%s y=%s\n' "$ox" "$oy"
        printf '    }\n'
        printf '}\n'
        printf '// blur_size is mapped to the niri blur offset (niri has no size).\n'
        printf 'blur {\n'
        printf '    passes %s\n' "$blur_passes"
        printf '    offset %s\n' "$blur_size"
        printf '}\n'
    } >"$tmp"

    mv -f "$tmp" "$OUT"
}

# update_state STATE KEY=VAL...: merge pairs, validating each value as a number.
update_state() {
    seed_state
    local state pair k v
    state="$(cat "$STATE")"
    for pair in "$@"; do
        k="${pair%%=*}"
        v="${pair#*=}"
        [[ "$k" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { err "invalid key: $k"; return 1; }
        jq -e --argjson v "$v" '.' >/dev/null 2>&1 <<<"$v" \
            || { err "invalid number for $k: $v"; return 1; }
        state="$(jq -c --arg k "$k" --argjson v "$v" '.[$k] = $v' <<<"$state")"
    done
    printf '%s\n' "$state"
}

save_state() {
    local tmp="$NIRI_CONFIG_DIR/.we-state.$$"
    printf '%s\n' "$1" >"$tmp"
    mv -f "$tmp" "$STATE"
}

reload() {
    [[ "${NIRI_NO_RELOAD:-0}" == "1" ]] && return 0
    if niri_validate; then
        niri_reload
    else
        warn "niri validate failed; not reloading"
    fi
}

cmd_read() {
    seed_state
    jq -r 'to_entries[] | "\(.key)=\(.value)"' "$STATE"
}

cmd_preview() {
    [[ $# -eq 0 ]] && return 0
    local state
    state="$(update_state "$@")" || return 1
    save_state "$state"
    write_kdl "$state"
    reload
    printf 'niri-effects: previewed %s\n' "$*"
}

cmd_persist() {
    seed_state
    write_kdl "$(cat "$STATE")"
    reload
    printf 'niri-effects: persisted\n'
}

cmd_apply() {
    cmd_preview "$@" || return 1
    cmd_persist
}

case "${1:-}" in
    read)    cmd_read ;;
    preview) shift; cmd_preview "$@" ;;
    persist) cmd_persist ;;
    apply)   shift; cmd_apply "$@" ;;
    -h|--help)
        echo "Usage: niri_effects.sh read | preview KEY=VAL ... | persist | apply KEY=VAL ..." >&2
        echo "Known keys: gaps_in gaps_out border_size blur_size blur_passes shadow_range shadow_offset_x shadow_offset_y" >&2
        ;;
    "")
        echo "Usage: niri_effects.sh read | preview KEY=VAL ... | persist | apply KEY=VAL ..." >&2
        exit 1
        ;;
    *) echo "unknown verb: $1" >&2; exit 1 ;;
esac
