#!/usr/bin/env bash
# ============================================================================
# niri_write_borders.sh - write generated/theme-colors.kdl and reload
# ============================================================================
# Translates the shell's border spec into niri KDL. The fragment deep-merges
# over the border block in modules/layout.kdl (theme-colors.kdl is included
# after the modules in config.kdl).
#
# Args (positional, all optional):
#   $1 active_hex   $2 active_alpha   $3 active_second  $4 active_angle
#   $5 inactive_hex $6 inactive_alpha $7 inactive_second $8 inactive_angle
#
# `hex` may include a leading '#'; `alpha` is a 2-digit hex string; `second` is
# the optional gradient second stop; `angle` is in degrees. When `second` is a
# 6-digit hex the border is written as an `active-gradient`/`inactive-gradient`
# (niri gradient syntax), otherwise as a solid color.
#
# Example:
#   niri_write_borders.sh fc618d ee 7bd88f 45 69676c aa "" 0
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'EOF'
Usage: niri_write_borders.sh [active_hex active_alpha active_second active_angle
                              inactive_hex inactive_alpha inactive_second inactive_angle]

Writes ~/.config/niri/generated/theme-colors.kdl and reloads.
Defaults: fc618d ee "" 0  69676c aa "" 0
EOF
    exit 0
fi

a_hex="${1:-fc618d}"; a_alpha="${2:-ee}"; a_second="${3:-}"; a_angle="${4:-0}"
i_hex="${5:-69676c}"; i_alpha="${6:-aa}"; i_second="${7:-}"; i_angle="${8:-0}"

ensure_dir "$NIRI_GENERATED_DIR"
OUT="$NIRI_GENERATED_DIR/theme-colors.kdl"

# color HEX ALPHA -> "#rrggbbaa"
color() { printf '#%s%s' "${1#\#}" "$2"; }

# line SLOT HEX ALPHA SECOND ANGLE
#   SLOT is "active" or "inactive"; prints a gradient when SECOND is hex.
line() {
    local slot="$1" hex="$2" alpha="$3" second="$4" angle="$5"
    if [[ "$second" =~ ^#?[0-9a-fA-F]{6}$ ]]; then
        printf '        %s-gradient from="%s" to="%s" angle=%s\n' \
            "$slot" "$(color "$hex" "$alpha")" "$(color "$second" "$alpha")" "${angle%%.*}"
    else
        printf '        %s-color "%s"\n' "$slot" "$(color "$hex" "$alpha")"
    fi
}

{
    printf '// Generated by niri_write_borders.sh - do not edit.\n'
    printf 'layout {\n'
    printf '    border {\n'
    line active   "$a_hex" "$a_alpha" "$a_second" "$a_angle"
    line inactive "$i_hex" "$i_alpha" "$i_second" "$i_angle"
    printf '    }\n'
    printf '}\n'
} >"$OUT"

# Saving a watched include reloads automatically; validate then force a reload
# so a bad fragment cannot break the running session.
if niri_validate; then
    niri_reload
else
    warn "niri validate failed after writing $OUT; not reloading"
fi
